### ISSUE TITLE
Run the client on port 80

### ISSUE THREAD

**Issue by sshagy** [tmintas/cubicon#6]
Isn't it better to run the client on port 80?

https://github.com/tmintas/cubicon/blob/4ca5b713a1d39c47ab2c4aac89a399bd78f20047/client/package.json#L29

Just ports 80 and 8080 are used by default for http, but of course, for a secure connection in the future, it is better to switch to https.

**Comment by tmintas** [comment]
This command is supposed to be used for running the client locally. To run the app in production mode you need to run 'npm build' and then serve the output folder with the js files. Have a look at https://www.copycat.dev/blog/reactjs-build-production/
